version: "3"

services:
  nginx:
    build:
     context: .
     dockerfile: Dockerfile.nginx
    ports:
     - 8080:81
  redis:
    image: redis
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    #image: jat7805/chimera-webapp:1.0
    ports:
      - "8081:80"
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    depends_on:
      - redis
  cliapp:
    build:
      context: .
      dockerfile: Dockerfile.cliapp
    #image: jat7805/chimera-cliapp:1.0
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    command: -r
    depends_on:
      - redis
